### ISSUE TITLE
Gendex permission error

### ISSUE THREAD

**Issue by alexcavazos67** [JustCarmen/fancy_gendex#8]
Can't create GENDEX file. I have created it manually and chmod 644 it. I still get:

/volume1/web/webt/modules_v3/fancy_gendex/app/FancyGendexClass.php:40 fopen(/volume1/web/webt/gendex.txt.tmp): failed to open stream: Permission denied

**Comment by JustCarmen** [comment]
Sorry for the delay, Somehow I've missed this message.

But to answer your question: Writing to the Gendex txt file is done in chunks to prevent server timeouts. Before writing to the final gendex.txt file the chunks are written to a temporary file (gendex.txt.tmp). This file only exists during the process. This means it is created each time. In your case this is a problem because the server doesn't allow php to write a file to the website root.

The Gendex.txt file needs to be in the root of the website in order to allow the genealogical search engines to read the file. That's why we can't place this file in the data-folder where we normally won't have this issue.

I think we can solve this issue by creating the temporary file inside the data folder in stead of in the root.
